/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain.tables;


import org.example.components.domain.Keys;
import org.example.components.domain.Public;
import org.example.components.domain.tables.records.ManufacturerRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Manufacturer extends TableImpl<ManufacturerRecord> {

    private static final long serialVersionUID = -1128638333;

    /**
     * The reference instance of <code>public.manufacturer</code>
     */
    public static final Manufacturer MANUFACTURER = new Manufacturer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManufacturerRecord> getRecordType() {
        return ManufacturerRecord.class;
    }

    /**
     * The column <code>public.manufacturer.id</code>.
     */
    public final TableField<ManufacturerRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('manufacturer_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.manufacturer.name</code>.
     */
    public final TableField<ManufacturerRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.manufacturer.status</code>.
     */
    public final TableField<ManufacturerRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("'MODERATION'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.manufacturer</code> table reference
     */
    public Manufacturer() {
        this(DSL.name("manufacturer"), null);
    }

    /**
     * Create an aliased <code>public.manufacturer</code> table reference
     */
    public Manufacturer(String alias) {
        this(DSL.name(alias), MANUFACTURER);
    }

    /**
     * Create an aliased <code>public.manufacturer</code> table reference
     */
    public Manufacturer(Name alias) {
        this(alias, MANUFACTURER);
    }

    private Manufacturer(Name alias, Table<ManufacturerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Manufacturer(Name alias, Table<ManufacturerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Manufacturer(Table<O> child, ForeignKey<O, ManufacturerRecord> key) {
        super(child, key, MANUFACTURER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<ManufacturerRecord, Long> getIdentity() {
        return Keys.IDENTITY_MANUFACTURER;
    }

    @Override
    public UniqueKey<ManufacturerRecord> getPrimaryKey() {
        return Keys.MANUFACTURER_PKEY;
    }

    @Override
    public List<UniqueKey<ManufacturerRecord>> getKeys() {
        return Arrays.<UniqueKey<ManufacturerRecord>>asList(Keys.MANUFACTURER_PKEY, Keys.MANUFACTURER_NAME_KEY);
    }

    @Override
    public Manufacturer as(String alias) {
        return new Manufacturer(DSL.name(alias), this);
    }

    @Override
    public Manufacturer as(Name alias) {
        return new Manufacturer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Manufacturer rename(String name) {
        return new Manufacturer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Manufacturer rename(Name name) {
        return new Manufacturer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
