/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.bom_id_seq</code>
     */
    public static final Sequence<Long> BOM_ID_SEQ = Internal.createSequence("bom_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.element_id_seq</code>
     */
    public static final Sequence<Long> ELEMENT_ID_SEQ = Internal.createSequence("element_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.element_type_id_seq</code>
     */
    public static final Sequence<Long> ELEMENT_TYPE_ID_SEQ = Internal.createSequence("element_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.footprint_id_seq</code>
     */
    public static final Sequence<Long> FOOTPRINT_ID_SEQ = Internal.createSequence("footprint_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.manufacturer_id_seq</code>
     */
    public static final Sequence<Long> MANUFACTURER_ID_SEQ = Internal.createSequence("manufacturer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.unit_id_seq</code>
     */
    public static final Sequence<Long> UNIT_ID_SEQ = Internal.createSequence("unit_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.unit_type_id_seq</code>
     */
    public static final Sequence<Long> UNIT_TYPE_ID_SEQ = Internal.createSequence("unit_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
