/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain;


import org.example.components.domain.tables.*;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bom</code>.
     */
    public static final Bom BOM = Bom.BOM;

    /**
     * The table <code>public.element</code>.
     */
    public static final Element ELEMENT = Element.ELEMENT;

    /**
     * The table <code>public.element_type</code>.
     */
    public static final ElementType ELEMENT_TYPE = ElementType.ELEMENT_TYPE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.footprint</code>.
     */
    public static final Footprint FOOTPRINT = Footprint.FOOTPRINT;

    /**
     * The table <code>public.manufacturer</code>.
     */
    public static final Manufacturer MANUFACTURER = Manufacturer.MANUFACTURER;

    /**
     * The table <code>public.unit</code>.
     */
    public static final Unit UNIT = Unit.UNIT;

    /**
     * The table <code>public.unit_type</code>.
     */
    public static final UnitType UNIT_TYPE = UnitType.UNIT_TYPE;
}
