/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain.tables.records;


import org.example.components.domain.tables.Footprint;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FootprintRecord extends UpdatableRecordImpl<FootprintRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 2017672914;

    /**
     * Setter for <code>public.footprint.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.footprint.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.footprint.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.footprint.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.footprint.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.footprint.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Footprint.FOOTPRINT.ID;
    }

    @Override
    public Field<String> field2() {
        return Footprint.FOOTPRINT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Footprint.FOOTPRINT.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public FootprintRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FootprintRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FootprintRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FootprintRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FootprintRecord
     */
    public FootprintRecord() {
        super(Footprint.FOOTPRINT);
    }

    /**
     * Create a detached, initialised FootprintRecord
     */
    public FootprintRecord(Long id, String name, String status) {
        super(Footprint.FOOTPRINT);

        set(0, id);
        set(1, name);
        set(2, status);
    }
}
