/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain.tables.records;


import org.example.components.domain.tables.Manufacturer;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManufacturerRecord extends UpdatableRecordImpl<ManufacturerRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -2075888320;

    /**
     * Setter for <code>public.manufacturer.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manufacturer.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.manufacturer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manufacturer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.manufacturer.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.manufacturer.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Manufacturer.MANUFACTURER.ID;
    }

    @Override
    public Field<String> field2() {
        return Manufacturer.MANUFACTURER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Manufacturer.MANUFACTURER.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public ManufacturerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ManufacturerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ManufacturerRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ManufacturerRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManufacturerRecord
     */
    public ManufacturerRecord() {
        super(Manufacturer.MANUFACTURER);
    }

    /**
     * Create a detached, initialised ManufacturerRecord
     */
    public ManufacturerRecord(Long id, String name, String status) {
        super(Manufacturer.MANUFACTURER);

        set(0, id);
        set(1, name);
        set(2, status);
    }
}
