/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain.tables.records;


import org.example.components.domain.tables.UnitType;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitTypeRecord extends UpdatableRecordImpl<UnitTypeRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 595913856;

    /**
     * Setter for <code>public.unit_type.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.unit_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.unit_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.unit_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UnitType.UNIT_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return UnitType.UNIT_TYPE.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UnitTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UnitTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UnitTypeRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitTypeRecord
     */
    public UnitTypeRecord() {
        super(UnitType.UNIT_TYPE);
    }

    /**
     * Create a detached, initialised UnitTypeRecord
     */
    public UnitTypeRecord(Long id, String name) {
        super(UnitType.UNIT_TYPE);

        set(0, id);
        set(1, name);
    }
}
