/*
 * This file is generated by jOOQ.
 */
package org.example.components.domain.tables.records;


import org.example.components.domain.tables.Unit;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitRecord extends UpdatableRecordImpl<UnitRecord> implements Record8<Long, Integer, String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = -508638000;

    /**
     * Setter for <code>public.unit.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.unit.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.unit.unit_type_id</code>.
     */
    public void setUnitTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.unit.unit_type_id</code>.
     */
    public Integer getUnitTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.unit.decimal_name</code>.
     */
    public void setDecimalName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.unit.decimal_name</code>.
     */
    public String getDecimalName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.unit.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.unit.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.unit.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.unit.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.unit.bomfiledata</code>.
     */
    public void setBomfiledata(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.unit.bomfiledata</code>.
     */
    public String getBomfiledata() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.unit.bomfilename</code>.
     */
    public void setBomfilename(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.unit.bomfilename</code>.
     */
    public String getBomfilename() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.unit.bomstatus</code>.
     */
    public void setBomstatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.unit.bomstatus</code>.
     */
    public String getBomstatus() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Integer, String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Integer, String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Unit.UNIT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Unit.UNIT.UNIT_TYPE_ID;
    }

    @Override
    public Field<String> field3() {
        return Unit.UNIT.DECIMAL_NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Unit.UNIT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Unit.UNIT.UPDATED_AT;
    }

    @Override
    public Field<String> field6() {
        return Unit.UNIT.BOMFILEDATA;
    }

    @Override
    public Field<String> field7() {
        return Unit.UNIT.BOMFILENAME;
    }

    @Override
    public Field<String> field8() {
        return Unit.UNIT.BOMSTATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUnitTypeId();
    }

    @Override
    public String component3() {
        return getDecimalName();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public String component6() {
        return getBomfiledata();
    }

    @Override
    public String component7() {
        return getBomfilename();
    }

    @Override
    public String component8() {
        return getBomstatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUnitTypeId();
    }

    @Override
    public String value3() {
        return getDecimalName();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public String value6() {
        return getBomfiledata();
    }

    @Override
    public String value7() {
        return getBomfilename();
    }

    @Override
    public String value8() {
        return getBomstatus();
    }

    @Override
    public UnitRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UnitRecord value2(Integer value) {
        setUnitTypeId(value);
        return this;
    }

    @Override
    public UnitRecord value3(String value) {
        setDecimalName(value);
        return this;
    }

    @Override
    public UnitRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UnitRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UnitRecord value6(String value) {
        setBomfiledata(value);
        return this;
    }

    @Override
    public UnitRecord value7(String value) {
        setBomfilename(value);
        return this;
    }

    @Override
    public UnitRecord value8(String value) {
        setBomstatus(value);
        return this;
    }

    @Override
    public UnitRecord values(Long value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitRecord
     */
    public UnitRecord() {
        super(Unit.UNIT);
    }

    /**
     * Create a detached, initialised UnitRecord
     */
    public UnitRecord(Long id, Integer unitTypeId, String decimalName, LocalDateTime createdAt, LocalDateTime updatedAt, String bomfiledata, String bomfilename, String bomstatus) {
        super(Unit.UNIT);

        set(0, id);
        set(1, unitTypeId);
        set(2, decimalName);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, bomfiledata);
        set(6, bomfilename);
        set(7, bomstatus);
    }
}
