spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/components"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}

logging:
  level:
    org.jooq: DEBUG
    org.example.components: DEBUG

storage:
  path: "storage"

frontend:
  url: http://localhost:3000/